solapi.enabled=true
solapi.api-key=NCSLFOCVDKQN2IJW
solapi.api-secret=YOUR7XFOD6LZ69EC9PWZ6UWFPL9EUQNR
solapi.pf-id=KA01PF250804013735940kl4bgcmEVao
solapi.template-id=KA01TP260320080919187FWHDx5pFqGL
solapi.security-template-id=KA01TP260416030530045TWLXCylRwE6
solapi.disable-sms=true
solapi.from=
solapi.endpoint=https://api.solapi.com/messages/v4/send-many/detail
solapi.button-name=방문 페이지 열기
solapi.button-url-mobile=http://ezat.iptime.org:6695/sample_pro/ez_in_out/take
solapi.button-url-pc=http://ezat.iptime.org:6695/sample_pro/ez_in_out/take
